# Generated by Django 3.1.5 on 2022-04-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('organizer', '0003_startup_data'),
    ]

    operations = [
    ]
