# Generated by Django 3.1.5 on 2022-04-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    TAGS = (
        #(tag name, tag slug)
        ("augmented reality", "augmented-reality")
    )

    def add_tag_data(apps, schema_editor):
        pass

    def remove_tag_data(apps, schema_editor):
        pass

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_tag_data,
            remove_tag_data
        )
    ]
